[package]
name        = "zydis"
version     = "0.0.1"
authors     = ["Joel Höner <joel@zyantific.com>"]

description = "Bindings for Zydis"
license     = "MIT"

build       = true

[build-dependencies]
gcc         = "0.3.53"
bindgen     = "0.29"
