[package]
name        = "zydis"
version     = "0.2.0"
authors     = ["Joel Höner <joel@zyantific.com>"]

description = "Bindings for Zydis"
license     = "MIT"

build       = true

[dependencies]
libc        = "*"

[build-dependencies]
gcc         = "0.3"
bindgen     = "0.29"
