[package]
name        = "zydis"
version     = "0.0.3"
authors     = [
    "Joel Höner <joel@zyantific.com>",
    "Timo von Hartz <c0untlizzi@gmail.com>"
]

description = "Bindings for Zydis"
license     = "MIT"
keywords    = ["disassembler", "x86", "amd64", "decoder"]
repository  = "https://github.com/zyantific/zydis-rs/"

build       = true

[build-dependencies]
cc          = "1.0"
bindgen     = "0.37"
