name: CI
on: [push, pull_request]

jobs:
  build_and_test:
    name: "${{ matrix.name }}"
    runs-on: "${{ matrix.image_name }}"

    strategy:
      matrix:
        include:
          - name: "macOS"
            image_name: "macOS-latest"
          - name: "Windows"
            image_name: "windows-2022"
          - name: "Linux (default features)"
            image_name: "ubuntu-22.04"
          - name: "Linux (all features)"
            image_name: "ubuntu-22.04"
            extra_args: "--all-features"
          - name: "Linux (minimal)"
            image_name: "ubuntu-22.04"
            extra_args: "--no-default-features"
          - name: "Linux (decoder only)"
            image_name: "ubuntu-22.04"
            extra_args: "--no-default-features --features full-decoder"
          - name: "Linux (encoder)"
            image_name: "ubuntu-22.04"
            extra_args: "--features encoder"

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: { submodules: recursive }
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: cargo build ${{ matrix.extra_args }}
      - name: Test
        run: cargo test ${{ matrix.extra_args }}
