name: CI
on: [push, pull_request]

jobs:
  build_and_test:
    name: zydis-rs
    runs-on: "${{ matrix.image_name }}"

    strategy:
      matrix:
        image_name: ["macOS-latest", "windows-2022", "ubuntu-22.04"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: { submodules: recursive }
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: cargo build
      - name: Test
        run: cargo test
